name: Playwright Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: make test
      - uses: actions/upload-artifact@v2
        if: always()
        timeout-minutes: 15
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
